// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: management.proto

package pb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GetServicesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetServicesRequest) Reset()         { *m = GetServicesRequest{} }
func (m *GetServicesRequest) String() string { return proto.CompactTextString(m) }
func (*GetServicesRequest) ProtoMessage()    {}
func (*GetServicesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_edc174f991dc0a25, []int{0}
}
func (m *GetServicesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetServicesRequest.Unmarshal(m, b)
}
func (m *GetServicesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetServicesRequest.Marshal(b, m, deterministic)
}
func (m *GetServicesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetServicesRequest.Merge(m, src)
}
func (m *GetServicesRequest) XXX_Size() int {
	return xxx_messageInfo_GetServicesRequest.Size(m)
}
func (m *GetServicesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetServicesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetServicesRequest proto.InternalMessageInfo

type GetServicesResponse struct {
	StatusCode           string                         `protobuf:"bytes,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ReasonCode           string                         `protobuf:"bytes,2,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	ReasonMessage        string                         `protobuf:"bytes,3,opt,name=reason_message,json=reasonMessage,proto3" json:"reason_message,omitempty"`
	Details              []*GetServicesResponse_Service `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *GetServicesResponse) Reset()         { *m = GetServicesResponse{} }
func (m *GetServicesResponse) String() string { return proto.CompactTextString(m) }
func (*GetServicesResponse) ProtoMessage()    {}
func (*GetServicesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_edc174f991dc0a25, []int{1}
}
func (m *GetServicesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetServicesResponse.Unmarshal(m, b)
}
func (m *GetServicesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetServicesResponse.Marshal(b, m, deterministic)
}
func (m *GetServicesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetServicesResponse.Merge(m, src)
}
func (m *GetServicesResponse) XXX_Size() int {
	return xxx_messageInfo_GetServicesResponse.Size(m)
}
func (m *GetServicesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetServicesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetServicesResponse proto.InternalMessageInfo

func (m *GetServicesResponse) GetStatusCode() string {
	if m != nil {
		return m.StatusCode
	}
	return ""
}

func (m *GetServicesResponse) GetReasonCode() string {
	if m != nil {
		return m.ReasonCode
	}
	return ""
}

func (m *GetServicesResponse) GetReasonMessage() string {
	if m != nil {
		return m.ReasonMessage
	}
	return ""
}

func (m *GetServicesResponse) GetDetails() []*GetServicesResponse_Service {
	if m != nil {
		return m.Details
	}
	return nil
}

type GetServicesResponse_Service struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetServicesResponse_Service) Reset()         { *m = GetServicesResponse_Service{} }
func (m *GetServicesResponse_Service) String() string { return proto.CompactTextString(m) }
func (*GetServicesResponse_Service) ProtoMessage()    {}
func (*GetServicesResponse_Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_edc174f991dc0a25, []int{1, 0}
}
func (m *GetServicesResponse_Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetServicesResponse_Service.Unmarshal(m, b)
}
func (m *GetServicesResponse_Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetServicesResponse_Service.Marshal(b, m, deterministic)
}
func (m *GetServicesResponse_Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetServicesResponse_Service.Merge(m, src)
}
func (m *GetServicesResponse_Service) XXX_Size() int {
	return xxx_messageInfo_GetServicesResponse_Service.Size(m)
}
func (m *GetServicesResponse_Service) XXX_DiscardUnknown() {
	xxx_messageInfo_GetServicesResponse_Service.DiscardUnknown(m)
}

var xxx_messageInfo_GetServicesResponse_Service proto.InternalMessageInfo

func (m *GetServicesResponse_Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetServicesResponse_Service) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type GetCountriesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCountriesRequest) Reset()         { *m = GetCountriesRequest{} }
func (m *GetCountriesRequest) String() string { return proto.CompactTextString(m) }
func (*GetCountriesRequest) ProtoMessage()    {}
func (*GetCountriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_edc174f991dc0a25, []int{2}
}
func (m *GetCountriesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCountriesRequest.Unmarshal(m, b)
}
func (m *GetCountriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCountriesRequest.Marshal(b, m, deterministic)
}
func (m *GetCountriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCountriesRequest.Merge(m, src)
}
func (m *GetCountriesRequest) XXX_Size() int {
	return xxx_messageInfo_GetCountriesRequest.Size(m)
}
func (m *GetCountriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCountriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCountriesRequest proto.InternalMessageInfo

type GetCountriesResponse struct {
	StatusCode           string                          `protobuf:"bytes,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ReasonCode           string                          `protobuf:"bytes,2,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	ReasonMessage        string                          `protobuf:"bytes,3,opt,name=reason_message,json=reasonMessage,proto3" json:"reason_message,omitempty"`
	Details              []*GetCountriesResponse_Country `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *GetCountriesResponse) Reset()         { *m = GetCountriesResponse{} }
func (m *GetCountriesResponse) String() string { return proto.CompactTextString(m) }
func (*GetCountriesResponse) ProtoMessage()    {}
func (*GetCountriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_edc174f991dc0a25, []int{3}
}
func (m *GetCountriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCountriesResponse.Unmarshal(m, b)
}
func (m *GetCountriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCountriesResponse.Marshal(b, m, deterministic)
}
func (m *GetCountriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCountriesResponse.Merge(m, src)
}
func (m *GetCountriesResponse) XXX_Size() int {
	return xxx_messageInfo_GetCountriesResponse.Size(m)
}
func (m *GetCountriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCountriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCountriesResponse proto.InternalMessageInfo

func (m *GetCountriesResponse) GetStatusCode() string {
	if m != nil {
		return m.StatusCode
	}
	return ""
}

func (m *GetCountriesResponse) GetReasonCode() string {
	if m != nil {
		return m.ReasonCode
	}
	return ""
}

func (m *GetCountriesResponse) GetReasonMessage() string {
	if m != nil {
		return m.ReasonMessage
	}
	return ""
}

func (m *GetCountriesResponse) GetDetails() []*GetCountriesResponse_Country {
	if m != nil {
		return m.Details
	}
	return nil
}

type GetCountriesResponse_Country struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCountriesResponse_Country) Reset()         { *m = GetCountriesResponse_Country{} }
func (m *GetCountriesResponse_Country) String() string { return proto.CompactTextString(m) }
func (*GetCountriesResponse_Country) ProtoMessage()    {}
func (*GetCountriesResponse_Country) Descriptor() ([]byte, []int) {
	return fileDescriptor_edc174f991dc0a25, []int{3, 0}
}
func (m *GetCountriesResponse_Country) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCountriesResponse_Country.Unmarshal(m, b)
}
func (m *GetCountriesResponse_Country) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCountriesResponse_Country.Marshal(b, m, deterministic)
}
func (m *GetCountriesResponse_Country) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCountriesResponse_Country.Merge(m, src)
}
func (m *GetCountriesResponse_Country) XXX_Size() int {
	return xxx_messageInfo_GetCountriesResponse_Country.Size(m)
}
func (m *GetCountriesResponse_Country) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCountriesResponse_Country.DiscardUnknown(m)
}

var xxx_messageInfo_GetCountriesResponse_Country proto.InternalMessageInfo

func (m *GetCountriesResponse_Country) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetCountriesResponse_Country) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*GetServicesRequest)(nil), "pb.GetServicesRequest")
	proto.RegisterType((*GetServicesResponse)(nil), "pb.GetServicesResponse")
	proto.RegisterType((*GetServicesResponse_Service)(nil), "pb.GetServicesResponse.Service")
	proto.RegisterType((*GetCountriesRequest)(nil), "pb.GetCountriesRequest")
	proto.RegisterType((*GetCountriesResponse)(nil), "pb.GetCountriesResponse")
	proto.RegisterType((*GetCountriesResponse_Country)(nil), "pb.GetCountriesResponse.Country")
}

func init() { proto.RegisterFile("management.proto", fileDescriptor_edc174f991dc0a25) }

var fileDescriptor_edc174f991dc0a25 = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x92, 0xb1, 0x4b, 0xc4, 0x30,
	0x14, 0x87, 0xe9, 0x5d, 0xbd, 0xc3, 0x77, 0x28, 0x12, 0x2b, 0x14, 0x97, 0x2b, 0x05, 0xe1, 0xa6,
	0x0c, 0xde, 0xa4, 0x6e, 0xde, 0xe0, 0xe4, 0x52, 0x37, 0x17, 0x49, 0xaf, 0x8f, 0xa3, 0x70, 0x4d,
	0x62, 0x5f, 0x72, 0xe0, 0x3f, 0x2d, 0xfe, 0x09, 0x42, 0x5e, 0x8a, 0x54, 0x1d, 0x9c, 0xdc, 0x92,
	0x8f, 0x6f, 0xf8, 0xe5, 0x23, 0x70, 0xd6, 0x29, 0xad, 0x76, 0xd8, 0xa1, 0x76, 0xd2, 0xf6, 0xc6,
	0x19, 0x31, 0xb1, 0x75, 0x99, 0x81, 0x78, 0x40, 0xf7, 0x84, 0xfd, 0xa1, 0xdd, 0x22, 0x55, 0xf8,
	0xea, 0x91, 0x5c, 0xf9, 0x9e, 0xc0, 0xf9, 0x08, 0x93, 0x35, 0x9a, 0x50, 0x2c, 0x61, 0x41, 0x4e,
	0x39, 0x4f, 0x2f, 0x5b, 0xd3, 0x60, 0x9e, 0x14, 0xc9, 0xea, 0xb8, 0x02, 0x46, 0x1b, 0xd3, 0x04,
	0xa1, 0x47, 0x45, 0x46, 0xb3, 0x30, 0x61, 0x81, 0x51, 0x10, 0xae, 0xe0, 0x34, 0x0a, 0x1d, 0x12,
	0xa9, 0x1d, 0xe6, 0xd3, 0xe0, 0x9c, 0x30, 0x7d, 0x64, 0x28, 0x6e, 0x60, 0xde, 0xa0, 0x53, 0xed,
	0x9e, 0xf2, 0xb4, 0x98, 0xae, 0x16, 0xd7, 0x4b, 0x69, 0x6b, 0xf9, 0xcb, 0x24, 0x19, 0x41, 0x35,
	0xf8, 0x97, 0x6b, 0x98, 0x47, 0x26, 0x04, 0xa4, 0x5a, 0x75, 0xc3, 0xce, 0x70, 0x16, 0x19, 0x1c,
	0x1d, 0xd4, 0xde, 0x0f, 0xdb, 0xf8, 0x52, 0x5e, 0x84, 0xf7, 0x6e, 0x8c, 0xd7, 0xae, 0x6f, 0xbf,
	0x3a, 0x7c, 0x24, 0x90, 0x8d, 0xf9, 0x7f, 0x87, 0xb8, 0xfd, 0x1e, 0xa2, 0x88, 0x21, 0x7e, 0x6c,
	0x92, 0x4c, 0xde, 0x46, 0x25, 0x22, 0xfb, 0x7b, 0x89, 0xfb, 0xd9, 0x73, 0x2a, 0xef, 0x6c, 0x5d,
	0xcf, 0xc2, 0x1f, 0x59, 0x7f, 0x06, 0x00, 0x00, 0xff, 0xff, 0xb8, 0x55, 0x4e, 0xd5, 0x37, 0x02,
	0x00, 0x00,
}
