// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: management.proto

package pb

import (
	fmt "fmt"
	math "math"
	proto "github.com/gogo/protobuf/proto"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *GetServicesRequest) Validate() error {
	return nil
}
func (this *GetServicesResponse) Validate() error {
	for _, item := range this.Details {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Details", err)
			}
		}
	}
	return nil
}
func (this *GetServicesResponse_Service) Validate() error {
	return nil
}
func (this *GetCountriesRequest) Validate() error {
	return nil
}
func (this *GetCountriesResponse) Validate() error {
	for _, item := range this.Details {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Details", err)
			}
		}
	}
	return nil
}
func (this *GetCountriesResponse_Country) Validate() error {
	return nil
}
