// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: product.proto

package pb

import (
	fmt "fmt"
	math "math"
	proto "github.com/gogo/protobuf/proto"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *ProductItem) Validate() error {
	return nil
}
func (this *GetListProductRequest) Validate() error {
	return nil
}
func (this *GetListProductResponse) Validate() error {
	for _, item := range this.Products {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Products", err)
			}
		}
	}
	return nil
}
func (this *GetProductDetailRequest) Validate() error {
	return nil
}
func (this *GetProductDetailResponse) Validate() error {
	if this.Product != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Product); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Product", err)
		}
	}
	return nil
}
func (this *CreateProductRequest) Validate() error {
	return nil
}
func (this *CreateProductResponse) Validate() error {
	return nil
}
func (this *UpdateProductRequest) Validate() error {
	return nil
}
func (this *UpdateProductResponse) Validate() error {
	return nil
}
func (this *DeleteProductRequest) Validate() error {
	return nil
}
func (this *DeleteProductResponse) Validate() error {
	return nil
}
