// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: product.proto

package pb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ProductItem struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Img                  string   `protobuf:"bytes,4,opt,name=img,proto3" json:"img,omitempty"`
	Categories           []string `protobuf:"bytes,5,rep,name=categories,proto3" json:"categories,omitempty"`
	Sizes                []string `protobuf:"bytes,6,rep,name=sizes,proto3" json:"sizes,omitempty"`
	Color                string   `protobuf:"bytes,7,opt,name=color,proto3" json:"color,omitempty"`
	Price                string   `protobuf:"bytes,8,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductItem) Reset()         { *m = ProductItem{} }
func (m *ProductItem) String() string { return proto.CompactTextString(m) }
func (*ProductItem) ProtoMessage()    {}
func (*ProductItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{0}
}
func (m *ProductItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductItem.Unmarshal(m, b)
}
func (m *ProductItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductItem.Marshal(b, m, deterministic)
}
func (m *ProductItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductItem.Merge(m, src)
}
func (m *ProductItem) XXX_Size() int {
	return xxx_messageInfo_ProductItem.Size(m)
}
func (m *ProductItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductItem.DiscardUnknown(m)
}

var xxx_messageInfo_ProductItem proto.InternalMessageInfo

func (m *ProductItem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ProductItem) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ProductItem) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ProductItem) GetImg() string {
	if m != nil {
		return m.Img
	}
	return ""
}

func (m *ProductItem) GetCategories() []string {
	if m != nil {
		return m.Categories
	}
	return nil
}

func (m *ProductItem) GetSizes() []string {
	if m != nil {
		return m.Sizes
	}
	return nil
}

func (m *ProductItem) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *ProductItem) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

type GetListProductRequest struct {
	Category             []string `protobuf:"bytes,1,rep,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListProductRequest) Reset()         { *m = GetListProductRequest{} }
func (m *GetListProductRequest) String() string { return proto.CompactTextString(m) }
func (*GetListProductRequest) ProtoMessage()    {}
func (*GetListProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{1}
}
func (m *GetListProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListProductRequest.Unmarshal(m, b)
}
func (m *GetListProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListProductRequest.Marshal(b, m, deterministic)
}
func (m *GetListProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListProductRequest.Merge(m, src)
}
func (m *GetListProductRequest) XXX_Size() int {
	return xxx_messageInfo_GetListProductRequest.Size(m)
}
func (m *GetListProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetListProductRequest proto.InternalMessageInfo

func (m *GetListProductRequest) GetCategory() []string {
	if m != nil {
		return m.Category
	}
	return nil
}

type GetListProductResponse struct {
	StatusCode           string         `protobuf:"bytes,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ReasonCode           string         `protobuf:"bytes,2,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	ReasonMessage        string         `protobuf:"bytes,3,opt,name=reason_message,json=reasonMessage,proto3" json:"reason_message,omitempty"`
	Products             []*ProductItem `protobuf:"bytes,4,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetListProductResponse) Reset()         { *m = GetListProductResponse{} }
func (m *GetListProductResponse) String() string { return proto.CompactTextString(m) }
func (*GetListProductResponse) ProtoMessage()    {}
func (*GetListProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{2}
}
func (m *GetListProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListProductResponse.Unmarshal(m, b)
}
func (m *GetListProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListProductResponse.Marshal(b, m, deterministic)
}
func (m *GetListProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListProductResponse.Merge(m, src)
}
func (m *GetListProductResponse) XXX_Size() int {
	return xxx_messageInfo_GetListProductResponse.Size(m)
}
func (m *GetListProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetListProductResponse proto.InternalMessageInfo

func (m *GetListProductResponse) GetStatusCode() string {
	if m != nil {
		return m.StatusCode
	}
	return ""
}

func (m *GetListProductResponse) GetReasonCode() string {
	if m != nil {
		return m.ReasonCode
	}
	return ""
}

func (m *GetListProductResponse) GetReasonMessage() string {
	if m != nil {
		return m.ReasonMessage
	}
	return ""
}

func (m *GetListProductResponse) GetProducts() []*ProductItem {
	if m != nil {
		return m.Products
	}
	return nil
}

type GetProductDetailRequest struct {
	ProductId            string   `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductDetailRequest) Reset()         { *m = GetProductDetailRequest{} }
func (m *GetProductDetailRequest) String() string { return proto.CompactTextString(m) }
func (*GetProductDetailRequest) ProtoMessage()    {}
func (*GetProductDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{3}
}
func (m *GetProductDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductDetailRequest.Unmarshal(m, b)
}
func (m *GetProductDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductDetailRequest.Marshal(b, m, deterministic)
}
func (m *GetProductDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductDetailRequest.Merge(m, src)
}
func (m *GetProductDetailRequest) XXX_Size() int {
	return xxx_messageInfo_GetProductDetailRequest.Size(m)
}
func (m *GetProductDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductDetailRequest proto.InternalMessageInfo

func (m *GetProductDetailRequest) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

type GetProductDetailResponse struct {
	StatusCode           string       `protobuf:"bytes,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ReasonCode           string       `protobuf:"bytes,2,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	ReasonMessage        string       `protobuf:"bytes,3,opt,name=reason_message,json=reasonMessage,proto3" json:"reason_message,omitempty"`
	Product              *ProductItem `protobuf:"bytes,4,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetProductDetailResponse) Reset()         { *m = GetProductDetailResponse{} }
func (m *GetProductDetailResponse) String() string { return proto.CompactTextString(m) }
func (*GetProductDetailResponse) ProtoMessage()    {}
func (*GetProductDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{4}
}
func (m *GetProductDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductDetailResponse.Unmarshal(m, b)
}
func (m *GetProductDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductDetailResponse.Marshal(b, m, deterministic)
}
func (m *GetProductDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductDetailResponse.Merge(m, src)
}
func (m *GetProductDetailResponse) XXX_Size() int {
	return xxx_messageInfo_GetProductDetailResponse.Size(m)
}
func (m *GetProductDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductDetailResponse proto.InternalMessageInfo

func (m *GetProductDetailResponse) GetStatusCode() string {
	if m != nil {
		return m.StatusCode
	}
	return ""
}

func (m *GetProductDetailResponse) GetReasonCode() string {
	if m != nil {
		return m.ReasonCode
	}
	return ""
}

func (m *GetProductDetailResponse) GetReasonMessage() string {
	if m != nil {
		return m.ReasonMessage
	}
	return ""
}

func (m *GetProductDetailResponse) GetProduct() *ProductItem {
	if m != nil {
		return m.Product
	}
	return nil
}

type CreateProductRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Categories           []string `protobuf:"bytes,3,rep,name=categories,proto3" json:"categories,omitempty"`
	Sizes                []string `protobuf:"bytes,4,rep,name=sizes,proto3" json:"sizes,omitempty"`
	Color                string   `protobuf:"bytes,5,opt,name=color,proto3" json:"color,omitempty"`
	Price                string   `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`
	Img                  string   `protobuf:"bytes,7,opt,name=img,proto3" json:"img,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProductRequest) Reset()         { *m = CreateProductRequest{} }
func (m *CreateProductRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProductRequest) ProtoMessage()    {}
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{5}
}
func (m *CreateProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductRequest.Unmarshal(m, b)
}
func (m *CreateProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductRequest.Marshal(b, m, deterministic)
}
func (m *CreateProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductRequest.Merge(m, src)
}
func (m *CreateProductRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProductRequest.Size(m)
}
func (m *CreateProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductRequest proto.InternalMessageInfo

func (m *CreateProductRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateProductRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateProductRequest) GetCategories() []string {
	if m != nil {
		return m.Categories
	}
	return nil
}

func (m *CreateProductRequest) GetSizes() []string {
	if m != nil {
		return m.Sizes
	}
	return nil
}

func (m *CreateProductRequest) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *CreateProductRequest) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *CreateProductRequest) GetImg() string {
	if m != nil {
		return m.Img
	}
	return ""
}

type CreateProductResponse struct {
	StatusCode           string   `protobuf:"bytes,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ReasonCode           string   `protobuf:"bytes,2,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	ReasonMessage        string   `protobuf:"bytes,3,opt,name=reason_message,json=reasonMessage,proto3" json:"reason_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProductResponse) Reset()         { *m = CreateProductResponse{} }
func (m *CreateProductResponse) String() string { return proto.CompactTextString(m) }
func (*CreateProductResponse) ProtoMessage()    {}
func (*CreateProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{6}
}
func (m *CreateProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductResponse.Unmarshal(m, b)
}
func (m *CreateProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductResponse.Marshal(b, m, deterministic)
}
func (m *CreateProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductResponse.Merge(m, src)
}
func (m *CreateProductResponse) XXX_Size() int {
	return xxx_messageInfo_CreateProductResponse.Size(m)
}
func (m *CreateProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductResponse proto.InternalMessageInfo

func (m *CreateProductResponse) GetStatusCode() string {
	if m != nil {
		return m.StatusCode
	}
	return ""
}

func (m *CreateProductResponse) GetReasonCode() string {
	if m != nil {
		return m.ReasonCode
	}
	return ""
}

func (m *CreateProductResponse) GetReasonMessage() string {
	if m != nil {
		return m.ReasonMessage
	}
	return ""
}

type UpdateProductRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Categories           []string `protobuf:"bytes,4,rep,name=categories,proto3" json:"categories,omitempty"`
	Sizes                []string `protobuf:"bytes,5,rep,name=sizes,proto3" json:"sizes,omitempty"`
	Color                string   `protobuf:"bytes,6,opt,name=color,proto3" json:"color,omitempty"`
	Price                string   `protobuf:"bytes,7,opt,name=price,proto3" json:"price,omitempty"`
	Img                  string   `protobuf:"bytes,9,opt,name=img,proto3" json:"img,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProductRequest) Reset()         { *m = UpdateProductRequest{} }
func (m *UpdateProductRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateProductRequest) ProtoMessage()    {}
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{7}
}
func (m *UpdateProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProductRequest.Unmarshal(m, b)
}
func (m *UpdateProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProductRequest.Marshal(b, m, deterministic)
}
func (m *UpdateProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProductRequest.Merge(m, src)
}
func (m *UpdateProductRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateProductRequest.Size(m)
}
func (m *UpdateProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProductRequest proto.InternalMessageInfo

func (m *UpdateProductRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateProductRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdateProductRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UpdateProductRequest) GetCategories() []string {
	if m != nil {
		return m.Categories
	}
	return nil
}

func (m *UpdateProductRequest) GetSizes() []string {
	if m != nil {
		return m.Sizes
	}
	return nil
}

func (m *UpdateProductRequest) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *UpdateProductRequest) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *UpdateProductRequest) GetImg() string {
	if m != nil {
		return m.Img
	}
	return ""
}

type UpdateProductResponse struct {
	StatusCode           string   `protobuf:"bytes,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ReasonCode           string   `protobuf:"bytes,2,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	ReasonMessage        string   `protobuf:"bytes,3,opt,name=reason_message,json=reasonMessage,proto3" json:"reason_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProductResponse) Reset()         { *m = UpdateProductResponse{} }
func (m *UpdateProductResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateProductResponse) ProtoMessage()    {}
func (*UpdateProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{8}
}
func (m *UpdateProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProductResponse.Unmarshal(m, b)
}
func (m *UpdateProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProductResponse.Marshal(b, m, deterministic)
}
func (m *UpdateProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProductResponse.Merge(m, src)
}
func (m *UpdateProductResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateProductResponse.Size(m)
}
func (m *UpdateProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProductResponse proto.InternalMessageInfo

func (m *UpdateProductResponse) GetStatusCode() string {
	if m != nil {
		return m.StatusCode
	}
	return ""
}

func (m *UpdateProductResponse) GetReasonCode() string {
	if m != nil {
		return m.ReasonCode
	}
	return ""
}

func (m *UpdateProductResponse) GetReasonMessage() string {
	if m != nil {
		return m.ReasonMessage
	}
	return ""
}

type DeleteProductRequest struct {
	ProductId            string   `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteProductRequest) Reset()         { *m = DeleteProductRequest{} }
func (m *DeleteProductRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteProductRequest) ProtoMessage()    {}
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{9}
}
func (m *DeleteProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteProductRequest.Unmarshal(m, b)
}
func (m *DeleteProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteProductRequest.Marshal(b, m, deterministic)
}
func (m *DeleteProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteProductRequest.Merge(m, src)
}
func (m *DeleteProductRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteProductRequest.Size(m)
}
func (m *DeleteProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteProductRequest proto.InternalMessageInfo

func (m *DeleteProductRequest) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

type DeleteProductResponse struct {
	StatusCode           string   `protobuf:"bytes,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ReasonCode           string   `protobuf:"bytes,2,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	ReasonMessage        string   `protobuf:"bytes,3,opt,name=reason_message,json=reasonMessage,proto3" json:"reason_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteProductResponse) Reset()         { *m = DeleteProductResponse{} }
func (m *DeleteProductResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteProductResponse) ProtoMessage()    {}
func (*DeleteProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{10}
}
func (m *DeleteProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteProductResponse.Unmarshal(m, b)
}
func (m *DeleteProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteProductResponse.Marshal(b, m, deterministic)
}
func (m *DeleteProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteProductResponse.Merge(m, src)
}
func (m *DeleteProductResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteProductResponse.Size(m)
}
func (m *DeleteProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteProductResponse proto.InternalMessageInfo

func (m *DeleteProductResponse) GetStatusCode() string {
	if m != nil {
		return m.StatusCode
	}
	return ""
}

func (m *DeleteProductResponse) GetReasonCode() string {
	if m != nil {
		return m.ReasonCode
	}
	return ""
}

func (m *DeleteProductResponse) GetReasonMessage() string {
	if m != nil {
		return m.ReasonMessage
	}
	return ""
}

func init() {
	proto.RegisterType((*ProductItem)(nil), "pb.ProductItem")
	proto.RegisterType((*GetListProductRequest)(nil), "pb.GetListProductRequest")
	proto.RegisterType((*GetListProductResponse)(nil), "pb.GetListProductResponse")
	proto.RegisterType((*GetProductDetailRequest)(nil), "pb.GetProductDetailRequest")
	proto.RegisterType((*GetProductDetailResponse)(nil), "pb.GetProductDetailResponse")
	proto.RegisterType((*CreateProductRequest)(nil), "pb.CreateProductRequest")
	proto.RegisterType((*CreateProductResponse)(nil), "pb.CreateProductResponse")
	proto.RegisterType((*UpdateProductRequest)(nil), "pb.UpdateProductRequest")
	proto.RegisterType((*UpdateProductResponse)(nil), "pb.UpdateProductResponse")
	proto.RegisterType((*DeleteProductRequest)(nil), "pb.DeleteProductRequest")
	proto.RegisterType((*DeleteProductResponse)(nil), "pb.DeleteProductResponse")
}

func init() { proto.RegisterFile("product.proto", fileDescriptor_f0fd8b59378f44a5) }

var fileDescriptor_f0fd8b59378f44a5 = []byte{
	// 465 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x95, 0x41, 0x8b, 0x13, 0x31,
	0x14, 0xc7, 0xc9, 0xcc, 0x74, 0xda, 0xbe, 0xb2, 0xab, 0x84, 0xae, 0x06, 0x41, 0x2d, 0x03, 0x42,
	0x45, 0xe8, 0xc1, 0x45, 0x10, 0xbc, 0xb9, 0x0b, 0xcb, 0x82, 0x82, 0x14, 0xbc, 0x78, 0x59, 0xa6,
	0x93, 0x47, 0x09, 0xb4, 0x4d, 0x4c, 0xd2, 0x83, 0x9e, 0xfc, 0x44, 0x7e, 0x08, 0x6f, 0x5e, 0xfd,
	0x44, 0x32, 0x49, 0x3a, 0x4c, 0x67, 0xa6, 0x7a, 0x59, 0xe6, 0xd6, 0xf7, 0x7f, 0x2f, 0xcd, 0x7b,
	0xbf, 0xf7, 0x0f, 0x03, 0x67, 0x4a, 0x4b, 0xbe, 0x2f, 0xec, 0x42, 0x69, 0x69, 0x25, 0x8d, 0xd4,
	0x2a, 0xfb, 0x4d, 0x60, 0xf2, 0xc9, 0xab, 0xb7, 0x16, 0xb7, 0xf4, 0x1c, 0x22, 0xc1, 0x19, 0x99,
	0x91, 0xf9, 0x78, 0x19, 0x09, 0x4e, 0xa7, 0x30, 0xb0, 0xc2, 0x6e, 0x90, 0x45, 0x4e, 0xf2, 0x01,
	0x9d, 0xc1, 0x84, 0xa3, 0x29, 0xb4, 0x50, 0x56, 0xc8, 0x1d, 0x8b, 0x5d, 0xae, 0x2e, 0xd1, 0x87,
	0x10, 0x8b, 0xed, 0x9a, 0x25, 0x2e, 0x53, 0xfe, 0xa4, 0xcf, 0x00, 0x8a, 0xdc, 0xe2, 0x5a, 0x6a,
	0x81, 0x86, 0x0d, 0x66, 0xf1, 0x7c, 0xbc, 0xac, 0x29, 0xe5, 0x4d, 0x46, 0x7c, 0x47, 0xc3, 0x52,
	0x97, 0xf2, 0x41, 0xa9, 0x16, 0x72, 0x23, 0x35, 0x1b, 0xfa, 0xfb, 0x5d, 0x50, 0xaa, 0x4a, 0x8b,
	0x02, 0xd9, 0xc8, 0xab, 0x2e, 0xc8, 0x2e, 0xe1, 0xe2, 0x06, 0xed, 0x07, 0x61, 0x6c, 0x98, 0x68,
	0x89, 0x5f, 0xf7, 0x68, 0x2c, 0x7d, 0x02, 0xa3, 0x70, 0xd1, 0x37, 0x46, 0xdc, 0xbf, 0x57, 0x71,
	0xf6, 0x93, 0xc0, 0xa3, 0xe6, 0x29, 0xa3, 0xe4, 0xce, 0x20, 0x7d, 0x0e, 0x13, 0x63, 0x73, 0xbb,
	0x37, 0x77, 0x85, 0xe4, 0x18, 0xa0, 0x80, 0x97, 0xae, 0x24, 0x77, 0x05, 0x1a, 0x73, 0x23, 0x77,
	0xbe, 0xc0, 0x23, 0x02, 0x2f, 0xb9, 0x82, 0x17, 0x70, 0x1e, 0x0a, 0xb6, 0x68, 0x4c, 0xbe, 0xc6,
	0x80, 0xea, 0xcc, 0xab, 0x1f, 0xbd, 0x48, 0x5f, 0xc1, 0x28, 0x6c, 0xc6, 0xb0, 0x64, 0x16, 0xcf,
	0x27, 0xaf, 0x1f, 0x2c, 0xd4, 0x6a, 0x51, 0xdb, 0xcb, 0xb2, 0x2a, 0xc8, 0xde, 0xc2, 0xe3, 0x1b,
	0x3c, 0xf4, 0x7a, 0x8d, 0x36, 0x17, 0x9b, 0xc3, 0x9c, 0x4f, 0x01, 0x42, 0xd9, 0x5d, 0xb5, 0xc4,
	0x71, 0x50, 0x6e, 0x79, 0x39, 0x2a, 0x6b, 0x1f, 0xed, 0x7b, 0xd8, 0x97, 0x30, 0x0c, 0x2d, 0x39,
	0x77, 0x74, 0xcc, 0x7a, 0xc8, 0x67, 0xbf, 0x08, 0x4c, 0xaf, 0x34, 0xe6, 0x16, 0x1b, 0x0b, 0xad,
	0x5c, 0x49, 0xfe, 0xe1, 0xca, 0xa8, 0xed, 0xca, 0x63, 0x0f, 0xc6, 0xa7, 0x3d, 0x98, 0x74, 0x7a,
	0x70, 0xd0, 0xe9, 0xc1, 0xb4, 0xe6, 0xc1, 0x83, 0xef, 0x87, 0x95, 0xef, 0xb3, 0x1f, 0x04, 0x2e,
	0x1a, 0x43, 0xf4, 0x8c, 0x3c, 0xfb, 0x43, 0x60, 0xfa, 0x59, 0xf1, 0x36, 0xc7, 0xfb, 0x7a, 0xed,
	0xc7, 0x5c, 0x93, 0xd3, 0x5c, 0x07, 0x9d, 0x5c, 0xd3, 0x4e, 0xae, 0xc3, 0x0e, 0xae, 0xe3, 0x63,
	0xae, 0x8d, 0xa1, 0xfa, 0xe6, 0xfa, 0x06, 0xa6, 0xd7, 0xb8, 0xc1, 0x16, 0xd6, 0xff, 0xbc, 0xc3,
	0xb2, 0xf3, 0xc6, 0xb9, 0x9e, 0x3b, 0x7f, 0x9f, 0x7e, 0x49, 0x16, 0xef, 0xd4, 0x6a, 0x95, 0xba,
	0x2f, 0xc1, 0xe5, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x61, 0x2c, 0xdf, 0xfb, 0x1a, 0x06, 0x00,
	0x00,
}
